import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import {
  ACCESS_FK_CONTRACT_CONSUMERS,
  ACCESS_FK_CONTRACT_MIGRATIONS,
  sealAccessFkContractReceipt
} from "./access-fk-contract-parity.mjs";

const repositoryRoot = fileURLToPath(new URL("../../", import.meta.url));
const evidencePath = path.join(repositoryRoot, "docs/evidence/access-fk-contract-parity-20260720.json");
const EXPECTED_CONTRACTS = ACCESS_FK_CONTRACT_MIGRATIONS;

const REAL_RECEIPT_ZERO_MISMATCH_FIELDS = Object.freeze([
  "missingTenants",
  "extraTenants",
  "statusMismatches",
  "sourceVersionMismatches",
  "currentEventIdMismatches",
  "referencedTenantIdsMissingSnapshot",
  "pendingOrDeadLetterEvents",
  "sourceVersionConflicts"
]);

test("provisional access FK contract stub has honest receipt shape", async () => {
  const receipt = JSON.parse(await readFile(evidencePath, "utf8"));
  assert.equal(receipt.kind, "access-fk-contract-parity");
  assert.equal(receipt.schemaVersion, 1);
  assert.equal(receipt.tipVersion, 15);
  assert.equal(receipt.tipMigration, "015-revoke-sofia-pulso-iris-control-plane-grants.sql");
  assert.deepEqual(receipt.contracts, [...EXPECTED_CONTRACTS]);
  assert.equal(receipt.status, "provisional-until-harness");
  assert.match(String(receipt.note ?? ""), /Stub only|Not a verified|Do not use as PULSO_ACCESS_FK_CONTRACT_RECEIPT/i);
  assert.equal(receipt.consumers, undefined);
  assert.notEqual(receipt.status, "verified");
  assert.ok(!receipt.closedDebts);
});

test("canonical seal helpers are stable for a real receipt shape", () => {
  const left = sealAccessFkContractReceipt({ z: 2, a: 1 });
  const right = sealAccessFkContractReceipt({ a: 1, z: 2 });
  assert.match(left.receiptSha256, /^[a-f0-9]{64}$/);
  assert.equal(left.receiptSha256, right.receiptSha256);
});

test("multi-consumer harness catalogs five distinct edges", () => {
  assert.equal(ACCESS_FK_CONTRACT_CONSUMERS.length, 5);
  assert.deepEqual(
    ACCESS_FK_CONTRACT_CONSUMERS.map((consumer) => consumer.id),
    ["channel", "iris", "sofia", "integration", "knowledge"]
  );
  const tokens = new Set(ACCESS_FK_CONTRACT_CONSUMERS.map((consumer) => consumer.tokenEnv));
  assert.equal(tokens.size, 5);
});

/**
 * A production-attested receipt (generated by the multi-consumer harness) must include
 * consumers.* with coverageBasisPoints 10000 and all mismatch fields at zero.
 * The checked-in stub intentionally omits consumers and must not be used as
 * PULSO_ACCESS_FK_CONTRACT_RECEIPT until that harness produces a sealed receipt.
 */
test("documents real multi-consumer receipt parity requirements", () => {
  assert.deepEqual(REAL_RECEIPT_ZERO_MISMATCH_FIELDS, [
    "missingTenants",
    "extraTenants",
    "statusMismatches",
    "sourceVersionMismatches",
    "currentEventIdMismatches",
    "referencedTenantIdsMissingSnapshot",
    "pendingOrDeadLetterEvents",
    "sourceVersionConflicts"
  ]);
  assert.equal(10_000, 10_000);
});
